# Generated by Django 2.0 on 2017-12-16 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='EthUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42)),
                ('name', models.CharField(max_length=42)),
                ('price', models.IntegerField()),
                ('last_price_date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Categories')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.EthUsers')),
            ],
        ),
        migrations.CreateModel(
            name='UserBought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='main.Products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.EthUsers')),
            ],
        ),
    ]
