# Generated by Django 2.0 on 2017-12-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171216_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
